= LettuSearch
:project-repo: RediSearch/lettusearch
:uri-repo: https://github.com/{project-repo}
ifdef::env-github[]
:badges:
:tag: master
:!toc-title:
:tip-caption: :bulb:
:note-caption: :paperclip:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

// Badges
ifdef::badges[]
image:https://img.shields.io/github/license/RediSearch/lettusearch.svg["License", link="https://github.com/RediSearch/lettusearch"]
image:https://img.shields.io/github/release/RediSearch/lettusearch.svg["Latest", link="https://github.com/RediSearch/lettusearch/releases/latest"]
image:https://github.com/RediSearch/lettusearch/workflows/CI/badge.svg["Actions", link="https://github.com/RediSearch/lettusearch/workflows/CI/badge.svg"]
image:https://codecov.io/gh/RediSearch/lettusearch/branch/master/graph/badge.svg["Codecov", link="https://codecov.io/gh/RediSearch/lettusearch"]
image:https://img.shields.io/lgtm/grade/java/g/RediSearch/lettusearch.svg?logo=lgtm&logoWidth=18["Language grade: Java", link="https://lgtm.com/projects/g/RediSearch/lettusearch/context:java"]
image:https://snyk.io/test/github/RediSearch/lettusearch/badge.svg?targetFile=build.gradle["Known Vulnerabilities", link="https://snyk.io/test/github/RediSearch/lettusearch?targetFile=build.gradle"]

image:https://img.shields.io/badge/Forum-RediSearch-blue["Forum", link=https://forum.redislabs.com/c/modules/redisearch/]
image:https://img.shields.io/discord/697882427875393627?style=flat-square["Discord", link="https://discord.gg/xTbqgTB"]
endif::[]

Java client for https://redisearch.io[RediSearch] based on https://lettuce.io[Lettuce]

Latest release: https://github.com/RediSearch/lettusearch/releases/latest

== Getting Started

Add LettuSearch to your application dependencies:

.Gradle
[source,groovy]
----
dependencies {
    implementation 'com.redislabs:lettusearch:x.y.x'
}
----

.Maven
[source,xml]
----
<dependency>
    <groupId>com.redislabs</groupId>
    <artifactId>lettusearch</artifactId>
    <version>x.y.z</version>
</dependency>
----

=== Basic Usage

[source,java]
----
RediSearchClient client = RediSearchClient.create(RedisURI.create(host, port)); // <1>
StatefulRediSearchConnection<String, String> connection = client.connect(); // <2>
RediSearchCommands<String, String> commands = connection.sync(); // <3>
commands.create("idx", Schema.<String>builder().field(TextField.<String>builder().name(NAME).build()).build()); // <4>
commands.add("idx", Document.<String, String>builder().id(ID).score(1D).field(NAME, "La Chouffe").build()); // <5>
SearchResults<String, String> results = commands.search("idx", "chou*"); // <6>
results.forEach(System.out::println);
----
<1> Create a RediSearch client
<2> Connect to RediSearch
<3> Use _sync_, _async_, or _reactive_ commands
<4> Create an index
<5> Add a document to the index
<6> Search the index

=== Pipelining

[source,java]
----
RediSearchClient client = RediSearchClient.create(RedisURI.create(host, port)); // <1>
StatefulRediSearchConnection<String, String> connection = client.connect(); // <2>
RediSearchAsyncCommands<String, String> commands = connection.async(); // <3>
commands.setAutoFlushCommands(false); // <4>
List<RedisFuture<?>> futures = new ArrayList<>();
for (Document<String, String> doc : docs) { // <5>
    RedisFuture<?> future = commands.add("idx", doc); // <6>
    futures.add(future);
}
commands.flushCommands(); // <7>
for (RedisFuture<?> future : futures) {
    try {
        future.get(1, TimeUnit.SECONDS); // <8>
    } catch (InterruptedException e) {
        log.debug("Command interrupted", e);
    } catch (ExecutionException e) {
        log.error("Could not execute command", e);
    } catch (TimeoutException e) {
        log.error("Command timed out", e);
    }
}
----
<1> Create a RediSearch client
<2> Connect to RediSearch
<3> Use async commands
<4> Disable command auto-flush
<5> Call commands to be executed in a pipeline
<6> Add command execution future to the list  
<7> Flush commands
<8> Wait for response from each future

=== Connection pooling

[source,java]
----
RediSearchClient client = RediSearchClient.create(RedisURI.create(host, port)); // <1>
GenericObjectPoolConfig<StatefulRediSearchConnection<String, String>> config = new GenericObjectPoolConfig<>(); // <2>
config.setMaxTotal(8);
GenericObjectPool<StatefulRediSearchConnection<String, String>> pool = ConnectionPoolSupport.createGenericObjectPool(client::connect, config); // <3>
// The connection pool can now be passed to worker threads
try (StatefulRediSearchConnection<String, String> connection = pool.borrowObject()) { // <4>
    RediSearchCommands<String, String> commands = connection.sync(); // <5>
    commands.search("idx", "*"); // <6>
}
----
<1> Create a RediSearch client
<2> Create a pool configuration
<3> Create the connection pool
<4> In worker threads, get connections in a try-with statement to automatically return them to the pool 
<5> Use _sync_ commands
<6> Execute commands

