// suppress inspection "SyntaxError" for whole file
= LettuSearch
:source-highlighter: coderay
// Metadata
:release-version: 1.4.0
// Settings
:idprefix:
:idseparator: -
ifndef::env-github[:icons: font]
// URIs
:project-repo: RediSearch/lettusearch
:uri-repo: https://github.com/{project-repo}
// GitHub customization
ifdef::env-github[]
:badges:
:tag: master
:!toc-title:
:tip-caption: :bulb:
:note-caption: :paperclip:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

// Badges
ifdef::badges[]
image:https://img.shields.io/github/license/RediSearch/lettusearch.svg["License", link="https://github.com/RediSearch/lettusearch"]
image:https://img.shields.io/github/release/RediSearch/lettusearch.svg["GitHub issues", link="https://github.com/RediSearch/lettusearch/releases/latest"]
image:https://github.com/RediSearch/lettusearch/workflows/Java%20CI%20with%20Gradle/badge.svg["Actions", link="https://github.com/RediSearch/lettusearch/workflows/Java%20CI%20with%20Gradle/badge.svg"]
image:https://maven-badges.herokuapp.com/maven-central/com.redislabs/lettusearch/badge.svg["Maven Central", link="https://maven-badges.herokuapp.com/maven-central/com.redislabs/lettusearch"]
image:https://www.javadoc.io/badge/com.redislabs/lettusearch.svg["Javadocs", link="https://www.javadoc.io/doc/com.redislabs/lettusearch"]
image:https://codecov.io/gh/RediSearch/lettusearch/branch/master/graph/badge.svg["Codecov", link="https://codecov.io/gh/RediSearch/lettusearch"]
image:https://img.shields.io/lgtm/grade/java/g/RediSearch/lettusearch.svg?logo=lgtm&logoWidth=18["Language grade: Java", link="https://lgtm.com/projects/g/RediSearch/lettusearch/context:java"]
image:https://snyk.io/test/github/RediSearch/lettusearch/badge.svg?targetFile=build.gradle["Known Vulnerabilities", link="https://snyk.io/test/github/RediSearch/lettusearch?targetFile=build.gradle"]

image:https://img.shields.io/badge/Forum-RediSearch-blue["Forum", https://forum.redislabs.com/c/modules/redisearch/]
image:https://badges.gitter.im/RedisLabs/RediSearch.svg["Gitter", link="https://gitter.im/RedisLabs/RediSearch?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge"]
endif::[]

Java client for https://redisearch.io[RediSearch] based on https://lettuce.io[Lettuce]

Latest release: https://github.com/RediSearch/lettusearch/releases/latest

== Getting Started

Add LettuSearch to your application dependencies:

.Gradle
[source,groovy]
----
dependencies {
    implementation 'com.redislabs:lettusearch:x.y.x'
}
----

.Maven
[source,xml]
----
<dependency>
    <groupId>com.redislabs</groupId>
    <artifactId>lettusearch</artifactId>
    <version>x.y.z</version>
</dependency>
----

Usage example:
[source,java]
----
RediSearchClient client = RediSearchClient.create("redis://localhost"); //<1>
StatefulRediSearchConnection<String, String> connection = client.connect(); //<2>
RediSearchCommands<String, String> commands = connection.sync(); //<3>
commands.create(INDEX, Schema.builder().field(TextField.builder().name(NAME).build()).build()); //<4>
commands.add(INDEX, Document.builder().id(ID).score(1D).field(NAME, "La Chouffe").build()); //<5>
SearchResults<String, String> results = commands.search(INDEX, "chou*"); //<6>
----
<1> Create a RediSearch client
<2> Connect to RediSearch
<3> Use _sync_, _async_, or _reactive_ API
<4> Create an index
<5> Add a document to the index
<6> Search the index

== Architecture
LettuSearch implements RediSearch commands using the https://lettuce.io/core/5.0.1.RELEASE/reference/#_custom_commands[Command abstraction] provided by Lettuce.

== Building
[source,shell]
----
$ gradle build
----
