// suppress inspection "SyntaxError" for whole file
= LettuSearch
:source-highlighter: coderay
// Metadata
:release-version: 1.4.0
// Settings
:idprefix:
:idseparator: -
ifndef::env-github[:icons: font]
// URIs
:project-repo: RediSearch/lettusearch
:uri-repo: https://github.com/{project-repo}
// GitHub customization
ifdef::env-github[]
:badges:
:tag: master
:!toc-title:
:tip-caption: :bulb:
:note-caption: :paperclip:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

// Badges
ifdef::badges[]
image:https://img.shields.io/github/license/RediSearch/lettusearch.svg["License", link="https://github.com/RediSearch/lettusearch"]
image:https://img.shields.io/github/release/RediSearch/lettusearch.svg["GitHub issues", link="https://github.com/RediSearch/lettusearch/releases/latest"]
image:https://circleci.com/gh/RediSearch/lettusearch/tree/master.svg?style=svg["CircleCI", link="https://circleci.com/gh/RediSearch/lettusearch/tree/master"]
image:https://maven-badges.herokuapp.com/maven-central/com.redislabs/lettusearch/badge.svg["Maven Central", link="https://maven-badges.herokuapp.com/maven-central/com.redislabs/lettusearch"]
image:https://www.javadoc.io/badge/com.redislabs/lettusearch.svg["Javadocs", link="https://www.javadoc.io/doc/com.redislabs/lettusearch"]

image:https://codecov.io/gh/RediSearch/lettusearch/branch/master/graph/badge.svg["Codecov", link="https://codecov.io/gh/RediSearch/lettusearch"]
image:https://img.shields.io/lgtm/grade/java/g/RediSearch/lettusearch.svg?logo=lgtm&logoWidth=18["Language grade: Java", link="https://lgtm.com/projects/g/RediSearch/lettusearch/context:java"]
image:https://snyk.io/test/github/RediSearch/lettusearch/badge.svg?targetFile=pom.xml["Known Vulnerabilities", link="https://snyk.io/test/github/RediSearch/lettusearch?targetFile=pom.xml"]
image:https://img.shields.io/badge/Mailing%20List-RediSearch-blue["Group", link="https://groups.google.com/forum/#!forum/redisearch"]
image:https://badges.gitter.im/RedisLabs/RediSearch.svg["Gitter", link="https://gitter.im/RedisLabs/RediSearch?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge"]
endif::[]

Java client for https://redisearch.io[RediSearch] based on https://lettuce.io[Lettuce]

== Architecture
LettuSearch implements RediSearch commands using the https://lettuce.io/core/5.0.1.RELEASE/reference/#_custom_commands[Command abstraction] provided by Lettuce.

== Building
[source,shell]
----
$ mvn clean install
----

== Usage
Add LettuSearch to your application dependencies, e.g. with Maven:
[source,xml]
----
<dependency>
	<groupId>com.redislabs</groupId>
	<artifactId>lettusearch</artifactId>
	<version>x.y.z</version>
</dependency>
----

.Java example
[source,java]
----
RediSearchCommands<String, String> ft = RediSearchClient.create("redis://localhost").connect().sync(); //<1>
ft.create("beers", Schema.builder().field(Field.text("name"))...); //<2>
ft.add("beers", "123", 1.0, Map.of("name", "La Chouffe", ...)); //<3>
SearchResults<String, String> results = ft.search("beers", "chouffe"); //<4>
----
<1> Establish a connection to RediSearch and use _sync_, _async_, or _reactive_ API
<3> Create a RediSearch index
<4> Add documents to the previously created index
<5> Search the index
