// suppress inspection "SyntaxError" for whole file
= LettuSearch
:source-highlighter: coderay
// Metadata
:release-version: 1.4.0
// Settings
:idprefix:
:idseparator: -
ifndef::env-github[:icons: font]
// URIs
:project-repo: RediSearch/lettusearch
:uri-repo: https://github.com/{project-repo}
// GitHub customization
ifdef::env-github[]
:badges:
:tag: master
:!toc-title:
:tip-caption: :bulb:
:note-caption: :paperclip:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

// Badges
ifdef::badges[]
image:https://img.shields.io/github/license/RediSearch/lettusearch.svg["License", link="https://github.com/RediSearch/lettusearch"]
image:https://img.shields.io/github/release/RediSearch/lettusearch.svg["GitHub issues", link="https://github.com/RediSearch/lettusearch/releases/latest"]
image:https://circleci.com/gh/RediSearch/lettusearch/tree/master.svg?style=svg["CircleCI", link="https://circleci.com/gh/RediSearch/lettusearch/tree/master"]
image:https://maven-badges.herokuapp.com/maven-central/com.redislabs/lettusearch/badge.svg["Maven Central", link="https://maven-badges.herokuapp.com/maven-central/com.redislabs/lettusearch"]
image:https://www.javadoc.io/badge/com.redislabs/lettusearch.svg["Javadocs", link="https://www.javadoc.io/doc/com.redislabs/lettusearch"]

image:https://codecov.io/gh/RediSearch/lettusearch/branch/master/graph/badge.svg["Codecov", link="https://codecov.io/gh/RediSearch/lettusearch"]
image:https://img.shields.io/lgtm/grade/java/g/RediSearch/lettusearch.svg?logo=lgtm&logoWidth=18["Language grade: Java", link="https://lgtm.com/projects/g/RediSearch/lettusearch/context:java"]
image:https://snyk.io/test/github/RediSearch/lettusearch/badge.svg?targetFile=pom.xml["Known Vulnerabilities", link="https://snyk.io/test/github/RediSearch/lettusearch?targetFile=pom.xml"]
image:https://img.shields.io/badge/Mailing%20List-RediSearch-blue["Group", link="https://groups.google.com/forum/#!forum/redisearch"]
image:https://badges.gitter.im/RedisLabs/RediSearch.svg["Gitter", link="https://gitter.im/RedisLabs/RediSearch?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge"]
endif::[]

Java client for https://redisearch.io[RediSearch] based on https://lettuce.io[Lettuce]

== Getting Started

Add LettuSearch to your application dependencies:

.Gradle
[source,groovy]
----
dependencies {
    implementation 'com.redislabs:lettusearch:x.y.x'
}
----

.Maven
[source,xml]
----
<dependency>
	<groupId>com.redislabs</groupId>
	<artifactId>lettusearch</artifactId>
	<version>x.y.z</version>
</dependency>
----

Usage example:
[source,java]
----
RediSearchClient client = RediSearchClient.create("redis://localhost"); //<1>
StatefulRediSearchConnection<String, String> conn = client.connect(); //<2>
RediSearchCommands<String, String> commands = connection.sync(); //<3>
Schema schema = Schema.builder().field(TextField.name("field1").build())….build(); //<4>
CreateOptions options = CreateOptions.builder()….build();
ft.create("beerIdx", schema, options); //<5>
Document<String, String> doc = Document.<String, String>builder().id("123").score(1D).build(); //<6>
doc.put("name", "La Chouffe");
ft.add("beerIdx", doc); //<7>
SearchResults<String, String> results = ft.search("beerIdx", "chou*"); //<8>
----
<1> Create a RediSearch client
<2> Establish a connection to RediSearch
<3> Use _sync_, _async_, or _reactive_ API
<4> Create a schema
<5> Create an index with the schema
<6> Create a document
<7> Add document to the index
<8> Search the index

== Architecture
LettuSearch implements RediSearch commands using the https://lettuce.io/core/5.0.1.RELEASE/reference/#_custom_commands[Command abstraction] provided by Lettuce.

== Building
[source,shell]
----
$ gradle build
----